# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f111334d4fc58d204f599f595013ef7c5c78acdfc281458d7cfff9588e0bf22976316e1bc0f6e3bb4fcd797fd871c5a1a46c6df058d6c5d847bcaf0f504f9743
  hostname: dg.willjasen.com
  glass_client_id: 435863930723-5kbkucavfnuhh3egd796b9e6ltdtt7qj.apps.googleusercontent.com
  glass_client_secret: P7mPkMnEnONcli2oB9-58GBl
  dropcam_username: willjasen@gmail.com
  dropcam_password: PaRDb6ZxHx93xp62bCFbNRrxdwxKSrhA
test:
  secret_key_base: 5da7d5428f30fb5cb35ab6a5b9e0874ccbd26d1f4057b777317b73a5f20cc6a3be373dcbfddf0c08d90471ee3c5bb6cd16fc1beca66f250a6a84491238a69003

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
